Repository brain-tec/sale-reporting, pull requests merged in 2024-07, with the labels that each got.

#233 Syncing from upstream OCA/sale-reporting (16.0)
  sale_order_line_position/i18n/it.po
Labels: 16.0

#234 17.0 mig sale comment template
  sale_comment_template/README.rst
  sale_comment_template/__init__.py
  sale_comment_template/__manifest__.py
  sale_comment_template/i18n/de.po
  sale_comment_template/i18n/es.po
  sale_comment_template/i18n/fr.po
  sale_comment_template/i18n/it.po
  sale_comment_template/i18n/pt.po
  sale_comment_template/i18n/sale_comment_template.pot
  sale_comment_template/models/__init__.py
  sale_comment_template/models/sale_order.py
  sale_comment_template/pyproject.toml
  sale_comment_template/readme/CONTRIBUTORS.md
  sale_comment_template/readme/DESCRIPTION.md
  sale_comment_template/readme/INSTALL.md
  sale_comment_template/security/ir.model.access.csv
  sale_comment_template/static/description/icon.png
  sale_comment_template/static/description/index.html
  sale_comment_template/tests/__init__.py
  sale_comment_template/tests/test_sale_order_report.py
  sale_comment_template/views/base_comment_template_view.xml
  sale_comment_template/views/report_saleorder.xml
  sale_comment_template/views/sale_order_view.xml
Labels: 17.0.project_bo_543

#235 Syncing from upstream OCA/sale-reporting (17.0)
  README.md
  sale_comment_template/README.rst
  sale_comment_template/__init__.py
  sale_comment_template/__manifest__.py
  sale_comment_template/i18n/de.po
  sale_comment_template/i18n/es.po
  sale_comment_template/i18n/fr.po
  sale_comment_template/i18n/it.po
  sale_comment_template/i18n/pt.po
  sale_comment_template/i18n/sale_comment_template.pot
  sale_comment_template/models/__init__.py
  sale_comment_template/models/sale_order.py
  sale_comment_template/pyproject.toml
  sale_comment_template/readme/CONTRIBUTORS.md
  sale_comment_template/readme/DESCRIPTION.md
  sale_comment_template/readme/INSTALL.md
  sale_comment_template/security/ir.model.access.csv
  sale_comment_template/static/description/icon.png
  sale_comment_template/static/description/index.html
  sale_comment_template/tests/__init__.py
  sale_comment_template/tests/test_sale_order_report.py
  sale_comment_template/views/base_comment_template_view.xml
  sale_comment_template/views/report_saleorder.xml
  sale_comment_template/views/sale_order_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0
